### ISSUE TITLE
Decimal not supported.

### ISSUE THREAD

**Issue by borisdj** [ethanli83/EFSqlTranslator#26]
Getting
`System.NotImplementedException: 'Decimal not supported.'`
for this code:
````
var groupedItems = from p in context.Items.AsQueryable()
                   group p by p.CategoryId into GP
                   select new { CategoryId = GP.Key, Sum = GP.Sum(a => a.Value) };

var query = context.Query(groupedItem, new EFModelInfoProvider(context), new SqlObjectFactory());
var list = query.ToList();
````
**_Value_** is _decimal_ type.

**Comment by ethanli83** [comment]
Hi @borisdj,

I have fixed this issue in Translation.1.2.4. I will close the issue once you confirmed that it has been fix for you.

Thanks

**Comment by borisdj** [comment]
That now works, however there are few new errors, but they are similar so I will add them here:
1. If **_Value_** is _decimal?_(nullable) I get exception:

> Invalid cast from 'System.Decimal' to 'System.Nullable`1[[System.Decimal, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

I have tried to put
`Sum = GP.Sum(a => a != null ? a.Value : 0)`
but then I get

> Unable to cast object of type 'EFSqlTranslator.Translation.DbObjects.SqlObjects.SqlConstant' to type 'EFSqlTranslator.Translation.DbObjects.IDbSelectable

2. If **ItemId** is not int but is of type _Guid_ the error is:

> Guid not suported.

3. When in Entity there is Navigation property (_virtual **Company**_) I get error:
`Object Reference not set to an instance of an object.`
Code Sample:
````
public class Item
{
    public Guid ItemId { get; set; }

    [Required]
    [MaxLength(255)]
    public string Name { get; set; }

    public int CategoryId  { get; set; }

    public decimal? Value { get; set; }

    public DateTime? Timer { get; set; }
	
    public Guid CompanyId { get; set; }
    public virtual Company Company { get; set; }
}

public class Company
{
    public Guid CompanyId { get; set; }

    [Required]
    [MaxLength(255)]
    public string Name { get; set; }
}
````

**Comment by ethanli83** [comment]
Thanks @borisdj,

I will have a look at the nullable type, and the navigation property issues today after work. I have not implemented the ?: syntax yet. I will do it over the weekend if I get some time. 

Sorry if these errors is blocking you from do something.

**Comment by borisdj** [comment]
Thank you @ethanli83  as well for being prompt on the issues.

**Comment by ethanli83** [comment]
No problem at all, @borisdj.

I have just push a patch which adds support for Nullable type and Guid type. The version number is 1.2.5-rc1. I use 'rc' just in case there are more issues.

I was not able to replicate the navigation property iusse. Do you mind to give me an exampe?

Need to go to work now, so no more fun stuff for a while, kk.

Cheers

**Comment by borisdj** [comment]
I have checked the issues you said are fixed and they work.
1.  Here is the sample with Navigation error:
[link](https://www.dropbox.com/s/n15mfoywlkelowd/EFSqlTranslatorSample.zip?dl=0)
2. I can also confirm exception when selecting specific class instead of anonymous:
`select new /*SumClass*/`


2. In addition when Item is in another schema:
````
[Table(nameof(Item), Schema = "fin")]
public class Item
````
I am getting the following error:

> Message=Invalid object name 'Item'. Source=.Net SqlClient Data Provider
When you change schema by uncommenting `//[Table(nameof(Item), Schema = "fin")]`, you should also delete Migrations and recreate them. However even if you don't do that so soon as you remove this comment and run app you will get that error.

**Comment by ethanli83** [comment]
Hi, @borisdj 

I fixed some of the issues you mentioned in 1.2.5-rc2:

> 1. Here is the sample with Navigation error:

The reason for this error was that I was expecting relations are always have both parent and child relation. For example, if there is Company property in Item, the there should be Items property in Company. But is not the case in your example. For now, I will just default the to_column name to be the same as from_column name, if only the parent or child relation is defined.

> 2. In addition when _Item_ is in another _schema_

The schema name was not use in the query. I have fixed. Now your query will be translated as:
```
select i0.CategoryId, sum(i0.Value) as 'Sum'
from fin.Item i0
group by i0.CategoryId
```

Notes that in 'fin.Item', the schema 'fin' is included.

> 3. I can also confirm exception when selecting specific class instead of anonymous

This turns out to be a hard one as it is more related to the actual database provider and Dapper. Dapper does not handle this out of box. I will need to investigate into this issue a bit more. Not sure if I could figure out anything. It may have to be done as a getter and setter in Entity classes.

Let me know how you go with the fixes.

Cheers

**Comment by borisdj** [comment]
I've updated to 1.2.5-rc2 but I am'still getting both(1. and 2.) errors?

**Comment by ethanli83** [comment]
kk, my bad. You also need EFModels.1.1.2-rc1 package as well. This should fix the problem 1 & 2. 

I was not actually able to test no.2, as I could not figure out how to create database with two schemas using ef tool and MySql. Let me know if it does not work.

I made the library to support your setup which has only the parent relation but no child relation. So you should not need add Items in Company entity anymore.

**Comment by borisdj** [comment]
With EFModels.1.1.2-rc1 they are both fixed.
Great work.

PS
Do you want me to move ibug 3.(class instead of anonymous) to another new issue so that you could close this one?

**Comment by ethanli83** [comment]
Great!, thank you @borisdj.

> Do you want me to move bug 3.(class instead of anonymous) to another new issue so that you could close this one? 

Yes, please, thank you. kk

> And should this bug be fixed in the Dapper lib? In the meantime do you think a patch could be made, whether in your lib or in the project that is using these libraries?

There is a open Dapper issue for this already, so hopefully they will fix it. By the meamtime, I discovered some thing call SqlMapper.TypeHandler which may solve the issue for us. It is a Dapper feature which interferes type convertion. You use it like this.

```
// first add this class to your project
public class GuidTypeHandler : SqlMapper.TypeHandler<Guid>
{
    public override Guid Parse(object value)
    {
        var inVal = (byte[])value;
        byte[] outVal = new byte[] { inVal[3], inVal[2], inVal[1], inVal[0], inVal[5], inVal[4], inVal[7], inVal[6], inVal[8], inVal[9], inVal[10], inVal[11], inVal[12], inVal[13], inVal[14], inVal[15] };
        return new Guid(outVal);
    }

    public override void SetValue(System.Data.IDbDataParameter parameter, Guid value)
    {
        var inVal = value.ToByteArray();
        byte[] outVal = new byte[] { inVal[3], inVal[2], inVal[1], inVal[0], inVal[5], inVal[4], inVal[7], inVal[6], inVal[8], inVal[9], inVal[10], inVal[11], inVal[12], inVal[13], inVal[14], inVal[15] };
        parameter.Value = outVal;
    }
}
```
Then you add follow line at where you app beigns to run (maybe Startup.cs).
```
SqlMapper.AddTypeHandler<Guid>(new GuidTypeHandler());
```
The Dapper will be able to convert byte[] to Guid.

Let me know if this helps.

**Comment by borisdj** [comment]
You could close this issue since I've moved remaining task to new issue.

**Comment by ethanli83** [comment]
@borisdj, cool, thanks. By the way, did you try the TypeHandler?

**Comment by borisdj** [comment]
Yes but it didn't solved the problem with select to Class after grouping.
As I have explained in the newly created task, bug exist even with _int_ instead of _Guid_.

**Comment by ethanli83** [comment]
No worries, I will have a look. Thanks~
